# For docker deployment using image
name: compoviz

services:
  prod:
    image: ghcr.io/adavesik/compoviz:latest
    container_name: compoviz
    restart: unless-stopped
    ports:
      - "8080:80"
    labels:
      # Runtipi-compatible labels
      runtipi.managed: "true"
      traefik.enable: "true"
      traefik.http.routers.compoviz.rule: PathPrefix("/")
      traefik.http.services.compoviz.loadbalancer.server.port: "80"